### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by ilyalasy** [wenhuchen/KGPT#6]
Hey, downloaded your pretrained weights from recent Google Drive link and ran script specified in [reproducing results](https://github.com/wenhuchen/KGPT#reproducing-our-results). Got this error:
```
Traceback (most recent call last):
  File "code/run.py", line 453, in <module>
    result = model.module.beam_search(data[:-2], tokenizer, n_bm=args.beam_size, banwords=banwords, max_token_seq_len=args.max_dec_len)
  File "/home/ilya/repos/KGPT/code/Model.py", line 646, in beam_search
    active_inst_idx_list = beam_decode_step(self, inst_dec_beams, len_dec_seq, active_inst_idx_list,
  File "/home/ilya/repos/KGPT/code/Model.py", line 883, in beam_decode_step
    dec_partial_seq = [inst_dec_beams[idx].get_current_state() 
  File "/home/ilya/repos/KGPT/code/Model.py", line 883, in <listcomp>
    dec_partial_seq = [inst_dec_beams[idx].get_current_state() 
  File "/home/ilya/repos/KGPT/code/Model.py", line 34, in get_current_state
    return self.get_tentative_hypothesis()
  File "/home/ilya/repos/KGPT/code/Model.py", line 103, in get_tentative_hypothesis
    hyps = [self.get_hypothesis(k) for k in keys]
  File "/home/ilya/repos/KGPT/code/Model.py", line 103, in <listcomp>
    hyps = [self.get_hypothesis(k) for k in keys]
  File "/home/ilya/repos/KGPT/code/Model.py", line 114, in get_hypothesis
    hyp.append(self.next_ys[j+1][k])
IndexError: tensors used as indices must be long, byte or bool tensors
```

**Comment by wenhuchen** [comment]
Please use the exact same version of Pytorch and Huggingface, that will solve the issue.

**Comment by ilyalasy** [comment]
Thanks for the quick answer, I will try to use exact versions.

**Comment by ilyalasy** [comment]
I'm using RTX 3070 and it seems it's only compatible with CUDA>=11.0 and cudnn>=8 which are not supported with Pytorch=1.4. Is it possible to fix this bug while using latest pytorch?

**Comment by ilyalasy** [comment]
Okay, added this line before line [113](https://github.com/wenhuchen/KGPT/blob/main/code/Model.py#L113) and it works.
```
if isinstance(k,torch.Tensor):
    k = int(k.item())
```

**Comment by wenhuchen** [comment]
I tried using another version. By adding this line, the program can run, but the score gets lower somehow. I would suggest you still use the designated version.
